name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Актуализация
        uses: actions/checkout@v2

      - name: Install buildx
        uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Извлечение версии 1С из файла
        shell: bash
        run: echo "::set-output name=version::$(cat ONEC_VERSION | tail -n1)"
        id: extract_version

      - name: Извлечение версии 1С для определения варинта сборки
        env: 
          ONEC_VERSION: ${{ steps.extract_version.outputs.version }}   
        shell: bash
        run: echo "::set-output name=version::$(echo ONEC_VERSION | cut -d'.' -f3)"
        id: build_version

      - name: Docker Login
        env:
          GITHUB_TOKEN: ${{ secrets.CR_PAT }}
        run: echo "${GITHUB_TOKEN}" | docker login ghcr.io --username thedemoncat --password-stdin

      - name: Push to GitHub Packages old version
        if: ${{ aVariablesteps.build_version.outputs.version < 20 }}"
        uses: docker/build-push-action@v2
        env: 
          ONEC_VERSION: ${{ steps.extract_version.outputs.version }}        
        with:
          context: .
          file: Dockerfile-deb
          build-args: |
            ONEC_USERNAME=${{ secrets.ONEC_USERNAME }}
            ONEC_PASSWORD=${{ secrets.ONEC_PASSWORD }}
            ONEC_VERSION=${{ steps.extract_version.outputs.version }}
          push: true
          tags: |
            ghcr.io/thedemoncat/onec-full:${{ steps.extract_version.outputs.version }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
 
      - name: Push to GitHub Packages new version
        if: {{ aVariablesteps.build_version.outputs.version > 19 }}
        uses: docker/build-push-action@v2
        env: 
          ONEC_VERSION: ${{ steps.extract_version.outputs.version }}        
        with:
          context: .
          file: Dockerfile
          build-args: |
            ONEC_USERNAME=${{ secrets.ONEC_USERNAME }}
            ONEC_PASSWORD=${{ secrets.ONEC_PASSWORD }}
            ONEC_VERSION=${{ steps.extract_version.outputs.version }}
          push: true
          tags: |
            ghcr.io/thedemoncat/onec-full:${{ steps.extract_version.outputs.version }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
 
        
        # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache